package Interfaces;

import javax.swing.JOptionPane;
import Utilidades.FechayHora;

public class MenuPrincipal extends javax.swing.JFrame {

    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        FechayHora Forma = new FechayHora();
        lblInfo.setText("Se ha accedido al sistema con el usuario ( " + Utilidades.Conexion.User + " ) el " + Forma.ObtenerFormato());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCapaBase = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        lblMiniSuper = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnConsultasBas = new javax.swing.JButton();
        pInfo = new javax.swing.JPanel();
        lblInfo = new javax.swing.JLabel();
        lblLogoTienda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pCapaBase.setBackground(new java.awt.Color(255, 207, 138));
        pCapaBase.setLayout(null);

        lblMenu.setFont(new java.awt.Font("Tw Cen MT", 3, 30)); // NOI18N
        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu.setText("Menu Principal");
        pCapaBase.add(lblMenu);
        lblMenu.setBounds(150, 100, 190, 30);

        lblMiniSuper.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        lblMiniSuper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMiniSuper.setText("Mini Super Flores");
        pCapaBase.add(lblMiniSuper);
        lblMiniSuper.setBounds(120, 60, 260, 40);

        btnCerrar.setBackground(new java.awt.Color(255, 102, 102));
        btnCerrar.setFont(new java.awt.Font("Tw Cen MT", 1, 22)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon("Imagenes\\IconoSalida.png"));
        btnCerrar.setText("<HTML>Cerrar Sesion</HTML>");
        btnCerrar.setToolTipText("");
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCerrar.setMargin(new java.awt.Insets(2, 16, 2, 14));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        pCapaBase.add(btnCerrar);
        btnCerrar.setBounds(160, 280, 170, 110);

        btnVentas.setFont(new java.awt.Font("Tw Cen MT", 1, 22)); // NOI18N
        btnVentas.setText("<html>Consultas<br>Predeterminadas</html>");
        btnVentas.setActionCommand("<html>Consultas<br>Predeterminadas</html>");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        pCapaBase.add(btnVentas);
        btnVentas.setBounds(280, 150, 170, 110);

        btnConsultasBas.setFont(new java.awt.Font("Tw Cen MT", 1, 22)); // NOI18N
        btnConsultasBas.setText("<html>Consultas</html>");
        btnConsultasBas.setActionCommand("");
        btnConsultasBas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasBasActionPerformed(evt);
            }
        });
        pCapaBase.add(btnConsultasBas);
        btnConsultasBas.setBounds(40, 150, 170, 110);

        pInfo.setBackground(new java.awt.Color(255, 255, 255));
        pInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pInfo.setMinimumSize(new java.awt.Dimension(492, 20));

        lblInfo.setBackground(new java.awt.Color(255, 255, 255));
        lblInfo.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N

        javax.swing.GroupLayout pInfoLayout = new javax.swing.GroupLayout(pInfo);
        pInfo.setLayout(pInfoLayout);
        pInfoLayout.setHorizontalGroup(
            pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInfoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pInfoLayout.setVerticalGroup(
            pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInfoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pCapaBase.add(pInfo);
        pInfo.setBounds(0, 430, 500, 20);

        lblLogoTienda.setIcon(new javax.swing.ImageIcon("../Imagenes/LogoTienda.jpg"));
        lblLogoTienda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pCapaBase.add(lblLogoTienda);
        lblLogoTienda.setBounds(310, 10, 156, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pCapaBase, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pCapaBase, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea cerrar la sesion?", "Cerrando sesion", 0, 2);
        if (x == 0) {
            InicioSesion frmSesion = new InicioSesion();
            frmSesion.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed

    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnConsultasBasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasBasActionPerformed
        ConsultasBasicas frmConsultasBasicas = new ConsultasBasicas();
        frmConsultasBasicas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultasBasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConsultasBas;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblLogoTienda;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMiniSuper;
    private javax.swing.JPanel pCapaBase;
    private javax.swing.JPanel pInfo;
    // End of variables declaration//GEN-END:variables
}
